#!/bin/bash

# get current directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# load config
source ${DIR}/CONFIG

# setup, if needed
if [ "$SET" != "Y" ]; then
	source ${DIR}/setup
fi

function change() {
	if [ "$1" == "S" ]; then
		COMMAND="chflags -R nohidden"
		LAST="S"
	else
		COMMAND="chflags -R hidden"
		LAST="H"
	fi
	cd
	for file in "$DEST"/*; do
		MATCH="F"
		if [ "$IGNORE" != "" ]; then
			for i in "${IGNORE[@]}"; do
				if [ "$file" == "$DEST/$i" ]; then
					MATCH="T"
				fi
			done
			if [ "$MATCH" == "F" ]; then
				eval "$COMMAND '$file'"
			fi
		else
			eval "$COMMAND '$file'"
		fi
	done
}

if [ "$1" != "-s" ] && [ "$1" != "-h" ] && [ "$1" != "-d" ] && [ "$1" != "-D" ] && [ "$1" != "-a" ] && [ "$1" != "-A" ] && [ "$AUTO" = "N" ] && [ "$1" != "-i" ] && [ "$1" != "-r" ]; then
	# validate the command
	echo "$(cat "${DIR}/INFO")"
elif [ "$AUTO" = "Y" ] && [ "$1" = "" ]; then
	# Auto Clean
	cd
	if [ "$LAST" = "S" ]; then
		change "H"
	else
		change "S"
	fi
else
	# option logic
	if [ "$1" = "-s" ]; then
		change "S"
	elif [ "$1" = "-h" ]; then
		change "h"
	elif [ "$1" = "-D" ]; then
		# show active directory
		echo "Directory to Clean is: $DEST"
	elif [ "$1" = "-A" ]; then
		# show if Auto Clean is enabled
		if [ "$AUTO" = "Y" ]; then
			echo "Auto Clean is currently enabled"
		else
			echo "Auto Clean is currently disabled"
		fi
	elif [ "$1" = "-a" ]; then
		# enable/disable Auto Clean
		if [ "$AUTO" = "Y" ]; then
			AUTO="N";
			echo "Auto Clean is now disabled"
		else
			AUTO="Y";
			echo "Auto Clean is now enabled"
		fi
	elif [ "$1" = "-i" ]; then
		# display info page
		echo "$(cat "${DIR}/INFO")"
	elif [ "$1" = "-d" ]; then
		# change active directory
		if [ -d "$2" ]; then
			DEST="$2"
			echo "Directory to Clean changed to: $2"
		else
			echo "Invalid directory... no changes applied"
		fi
	elif [ "$1" = "-r" ]; then
		# reset defaults
		echo "Reverting Clean to defaults."
		echo "Please run Clean without options to re-run setup."
		SET=N
	else
		# unknown error
		echo "Something went wrong!"
		echo "Run clean with -r to restore Clean to defaults"
	fi
fi

# write changes to config
echo "SET=$SET
DEST=$DEST
AUTO=$AUTO
LAST=$LAST" > ${DIR}/CONFIG

IGNORE_CNT=0;
for i in "${IGNORE[@]}"; do
	echo "IGNORE[$IGNORE_CNT]=\"$i\"" >> ${DIR}/CONFIG
	let "IGNORE_CNT++"
done
