#!/bin/bash

# get current directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# load config
source ${DIR}/CONFIG

# setup, if needed
if [ "$SET" != "Y" ]; then
	source ${DIR}/setup
fi

if [ "$1" != "-s" ] && [ "$1" != "-h" ] && [ "$1" != "-d" ] && [ "$1" != "-D" ] && [ "$1" != "-a" ] && [ "$1" != "-A" ] && [ "$AUTO" = "N" ] && [ "$1" != "-i" ] && [ "$1" != "-r" ]; then
	# validate the command
	echo "$(cat "${DIR}/INFO")"
elif [ "$AUTO" = "Y" ] && [ "$1" = "" ]; then
	# Auto Clean
	if [ "$LAST" = "S" ]; then
		for file in "$DEST"/*; do
			chflags -R hidden "$file"
		done
		LAST="H"
	else
		for file in "$DEST"/*; do
			chflags -R nohidden "$file"
		done
		LAST="S"
	fi
else
	# option logic
	if [ "$1" = "-s" ]; then
		# showing all
		for file in "$DEST"/*; do
			chflags -R nohidden "$file"
		done
		LAST="S"
	elif [ "$1" = "-h" ]; then
		for file in "$DEST"/*; do
			chflags -R hidden "$file"
		done
		LAST="H"
	elif [ "$1" = "-D" ]; then
		echo "Directory to Clean is: $DEST"
	elif [ "$1" = "-A" ]; then
		if [ "$AUTO" = "Y" ]; then
			echo "Auto Clean is currently enabled"
		else
			echo "Auto Clean is currently disabled"
		fi
	elif [ "$1" = "-a" ]; then
		if [ "$AUTO" = "Y" ]; then
			AUTO="N";
			echo "Auto Clean is now disabled"
		else
			AUTO="Y";
			echo "Auto Clean is now enabled"
		fi
	elif [ "$1" = "-i" ]; then
		echo "$(cat "${DIR}/INFO")"
	elif [ "$1" = "-d" ]; then
		if [ -d "$2" ]; then
			DEST="$2"
			echo "Directory to Clean changed to: $2"
		else
			echo "Invalid directory... no changes applied"
		fi
	elif [ "$1" = "-r" ]; then
		echo "Reverting Clean to defaults."
		echo "Please run Clean without options to re-run setup."
		SET=N
	else
		echo "Something went wrong!"
		echo "Run clean with -r to restore Clean to defaults"
	fi
fi

#write changes to config
echo "SET=$SET
DEST=$DEST
AUTO=$AUTO
LAST=$LAST" > ${DIR}/CONFIG