.TH HIDE 1
.SH NAME
hide \- clean up files and folders from the GUI
.SH SYNOPSIS
.B hide
[\fB\-s\fR]
[\fB\-h\fR]
[\fB\-d\fR \fDDEST\fR]
[\fB\-D\fR]
[\fB\-a\fR]
[\fB\-A\fR]
[\fB\-i\fR]
[\fB\-r\fR]
.SH DESCRIPTION
.B hide
clean up files and folders from the GUI
.SH OPTIONS
.TP
.BR \-s
Show the files of the current profile
.TP
.BR \-h
Hide the files of the current profile
.TP
.BR \-d " " =\fIDEST\fR
Change the current destination
.TP
.BR \-D
Show the current destination
.TP
.BR \-a
Enable/disable Auto hide: show/hide based on the current state
.TP
.BR \-A
Show if auto hide is enabled/disabled
.TP
.BR \-r
Restore hide to defaults