#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ANS=""

# load config
source ${DIR}/CONFIG

SET="Y"
DEST="Desktop/"
LAST="H"

echo "Thank you for installing Clean!"

while [ "$ANS" = "" ]; do
	read -p "Would you like to enable Auto Clean (y/n)? " ANS
	if [ "$ANS" = "y" ] || [ "$ANS" = "n" ] || [ "$ANS" = "Y" ] || [ "$ANS" = "N" ]; then
		if [ "$ANS" = "y" ] || [ "$ANS" = "Y" ]; then
			AUTO="Y"
		else
			AUTO="N"
		fi
		break
	else
		echo "Please respond with y/n..."
		ANS=""
	fi
done

ANS=""
while [ "$ANS" = "" ]; do
	read -e -p "What directory would you like to Clean? " ANS
	if [ -d "$ANS" ]; then
		DEST="$ANS"
	else
		echo "Not a valid directory..."
		ANS=""
	fi
done

#write changes to config
echo "SET=$SET
DEST=$DEST
AUTO=$AUTO
LAST=$LAST" > ${DIR}/CONFIG